# Generated by Django 4.2.30 on 2026-05-01 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('player_name', models.CharField(max_length=15, verbose_name='Имя игрока')),
                ('score', models.PositiveIntegerField(verbose_name='Очки')),
                ('rank', models.PositiveIntegerField(default=0, verbose_name='Ранг')),
                ('difficulty', models.CharField(choices=[('easy', 'Лёгкий'), ('medium', 'Средний'), ('hard', 'Сложный')], default='medium', max_length=10, verbose_name='Сложность')),
                ('date_achieved', models.DateTimeField(auto_now_add=True, verbose_name='Дата достижения')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaderboard_entries', to=settings.AUTH_USER_MODEL, verbose_name='Игрок')),
            ],
            options={
                'verbose_name': 'Запись в таблице лидеров',
                'verbose_name_plural': 'Таблица лидеров',
                'ordering': ['-score'],
            },
        ),
    ]
