# Generated by Django 4.2.30 on 2026-05-01 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('game_state', models.JSONField(default=dict, verbose_name='Состояние игры (JSON)')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='Очки')),
                ('level', models.PositiveIntegerField(default=1, verbose_name='Уровень')),
                ('time_played', models.PositiveIntegerField(default=0, verbose_name='Время в игре (сек)')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Завершена')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Игрок')),
            ],
            options={
                'verbose_name': 'Игровая сессия',
                'verbose_name_plural': 'Игровые сессии',
                'ordering': ['-score'],
            },
        ),
    ]
