# Generated by Django 6.0.4 on 2026-04-30 17:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('group_number', models.CharField(max_length=20, verbose_name='Группа')),
                ('subject', models.CharField(max_length=100, verbose_name='Предмет')),
                ('grade', models.IntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка')),
                ('date', models.CharField(help_text='Формат: ДД-ММ-ГГГГ', max_length=10, verbose_name='Дата (ДД-ММ-ГГГГ)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Оценка студента',
                'verbose_name_plural': 'Оценки студентов',
                'ordering': ['-created_at'],
                'unique_together': {('full_name', 'subject', 'date')},
            },
        ),
    ]
