# Generated by Django 6.0.4 on 2026-04-30 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentgrade',
            options={'ordering': ['-created_at'], 'verbose_name': 'Запись об успеваемости', 'verbose_name_plural': 'Записи об успеваемости'},
        ),
        migrations.AlterField(
            model_name='studentgrade',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='studentgrade',
            name='date',
            field=models.CharField(max_length=10, verbose_name='Дата сдачи (ДД-ММ-ГГГГ)'),
        ),
        migrations.AlterField(
            model_name='studentgrade',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='ФИО студента'),
        ),
        migrations.AlterField(
            model_name='studentgrade',
            name='group_number',
            field=models.CharField(max_length=20, verbose_name='Номер группы'),
        ),
    ]
